<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OCTI107.local" name="ProyectoMovil.Automatizacion.Ejecutar.Pruebas.EjecucionInicioPrueba" tests="2" failures="1" timestamp="26 Feb 2018 18:38:36 GMT" time="35.788" errors="1">
  <testcase name="EjecutarNavegacionGeneral" time="35.785" classname="ProyectoMovil.Automatizacion.Ejecutar.Pruebas.EjecucionInicioPrueba">
    <failure type="java.lang.AssertionError" message="Error QA: No se ha logrado validar en presionarSalirNotificaciones.
Parte de los componentes del aplicativo no son accesibles.
Revise el estado el ambiente de certificacion.
Presionar Salir de notificaciones no se realiza de manera correcta, revise que no tenga algun componente sobre o tenga una nombre de variable diferente.">
      <![CDATA[java.lang.AssertionError: Error QA: No se ha logrado validar en presionarSalirNotificaciones.
Parte de los componentes del aplicativo no son accesibles.
Revise el estado el ambiente de certificacion.
Presionar Salir de notificaciones no se realiza de manera correcta, revise que no tenga algun componente sobre o tenga una nombre de variable diferente.
	at org.testng.Assert.fail(Assert.java:94)
	at ProyectoMovil.Automatizacion.Ejecutar.Pruebas.EjecucionInicioPrueba.presionarSalirNotificaciones(EjecucionInicioPrueba.java:153)
	at ProyectoMovil.Automatizacion.Ejecutar.Pruebas.EjecucionInicioPrueba.EjecutarNavegacionGeneral(EjecucionInicioPrueba.java:590)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- EjecutarNavegacionGeneral -->
  <testcase name="EjecutarNavegacionGeneral" time="0.003" classname="ProyectoMovil.Automatizacion.Ejecutar.Pruebas.EjecucionInicioPrueba">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at ProyectoMovil.Automatizacion.Utilitario.AbstractTest.setup(AbstractTest.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- EjecutarNavegacionGeneral -->
</testsuite> <!-- ProyectoMovil.Automatizacion.Ejecutar.Pruebas.EjecucionInicioPrueba -->
